spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bugtracker
    username: psamolovov
    password: bugtracker,
    initialization-mode: always
  liquibase:
    change-log: classpath:liquibase/changeLog.xml
  # JPA properties
  jpa:
    properties:
      hibernate:
        temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    open-in-view: false
    generate-ddl: false